# SPDX-License-Identifier: GPL-2.0-only
# Generated by scripts/homebrew-formula.sh in seitzbg/mtr-rs; edit there, not here.
class MtrRs < Formula
  desc "Rust port of mtr (My TraceRoute) with a terminal UI and classic reports"
  homepage "https://github.com/seitzbg/mtr-rs"
  version "0.4.0"
  license "GPL-2.0-only"

  on_macos do
    on_arm do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.4.0/mtr-rs-0.4.0-aarch64-macos.tar.gz"
      sha256 "6c41f27094f12dd1367351bba395ba05d03ea3abcea4a28b3d5f6f121a1d9533"
    end
    on_intel do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.4.0/mtr-rs-0.4.0-x86_64-macos.tar.gz"
      sha256 "63ed12894af6da7bbb02a42769947d3ec7f38560bd9294feda3e41d587c570e5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.4.0/mtr-rs-0.4.0-aarch64-linux.tar.gz"
      sha256 "2f5f2de31b07b69208202f6ea70b708dcbd370c3146fb86be9446b6ff25d04b5"
    end
    on_intel do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.4.0/mtr-rs-0.4.0-x86_64-linux.tar.gz"
      sha256 "8d4c1274b56935944c96f41f788d3643d34237cce9c6c6aabbb7e8050a3a6d57"
    end
  end

  def install
    bin.install "bin/mtr-rs", "bin/mtr-rs-packet"
    man8.install "man/mtr-rs.8", "man/mtr-rs-packet.8"
    bash_completion.install "completions/mtr-rs.bash" => "mtr-rs"
    zsh_completion.install "completions/_mtr-rs"
    fish_completion.install "completions/mtr-rs.fish"
  end

  def caveats
    # Accumulate rather than return from the last on_* block: on macOS that block is the
    # on_linux one, whose value is nil, and the caveat would silently vanish.
    text = +""
    on_macos do
      text << <<~EOS
        mtr-rs-packet opens raw sockets, which need root. Either run `sudo mtr-rs`, or let
        the helper start as root on its own (it drops back to you once its sockets are open);
        Homebrew cannot do that step, so repeat it after every install or upgrade:
          sudo chown root:wheel #{opt_bin}/mtr-rs-packet && sudo chmod u+s #{opt_bin}/mtr-rs-packet
      EOS
    end
    on_linux do
      text << <<~EOS
        mtr-rs-packet needs cap_net_raw for raw sockets; grant it once per install or upgrade:
          sudo setcap cap_net_raw+ep #{opt_bin}/mtr-rs-packet
        Without it the helper falls back to unprivileged ICMP sockets (see the README).
      EOS
    end
    text
  end

  test do
    assert_match "mtr-rs #{version}", shell_output("#{bin}/mtr-rs --version")
    assert_match "Usage: mtr-rs", shell_output("#{bin}/mtr-rs --help")
  end
end
