# SPDX-License-Identifier: GPL-2.0-only
# Generated by scripts/homebrew-formula.sh in seitzbg/mtr-rs; edit there, not here.
class MtrRs < Formula
  desc "Rust port of mtr (My TraceRoute) with a terminal UI and classic reports"
  homepage "https://github.com/seitzbg/mtr-rs"
  version "0.3.0"
  license "GPL-2.0-only"

  on_macos do
    on_arm do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.3.0/mtr-rs-0.3.0-aarch64-macos.tar.gz"
      sha256 "9eae1561826a1d2fe44b2ba376aa6546b6318cff7bad4b5d1e1ee6ad0b91778f"
    end
    on_intel do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.3.0/mtr-rs-0.3.0-x86_64-macos.tar.gz"
      sha256 "0570e817b6ba633de6f02264a622e7ec59bb32d6953c52178a24384f0b22999d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.3.0/mtr-rs-0.3.0-aarch64-linux.tar.gz"
      sha256 "3170462cbd7c37f88fd3064cf961a2c6479da001748d7f96781e34a66bd5ff3d"
    end
    on_intel do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.3.0/mtr-rs-0.3.0-x86_64-linux.tar.gz"
      sha256 "18b7e977a80c13959ef8b36082ec83515b03b5cf30c24f5dfeb12f99df8b59d2"
    end
  end

  def install
    bin.install "bin/mtr-rs", "bin/mtr-rs-packet"
    man8.install "man/mtr-rs.8", "man/mtr-rs-packet.8"
    bash_completion.install "completions/mtr-rs.bash" => "mtr-rs"
    zsh_completion.install "completions/_mtr-rs"
    fish_completion.install "completions/mtr-rs.fish"
  end

  def caveats
    on_macos do
      <<~EOS
        mtr-rs-packet opens raw sockets, which need root. Either run `sudo mtr-rs`, or let
        the helper start as root on its own (it drops back to you once its sockets are open);
        Homebrew cannot do that step, so repeat it after every install or upgrade:
          sudo chown root:wheel #{opt_bin}/mtr-rs-packet && sudo chmod u+s #{opt_bin}/mtr-rs-packet
      EOS
    end
    on_linux do
      <<~EOS
        mtr-rs-packet needs cap_net_raw for raw sockets; grant it once per install or upgrade:
          sudo setcap cap_net_raw+ep #{opt_bin}/mtr-rs-packet
        Without it the helper falls back to unprivileged ICMP sockets (see the README).
      EOS
    end
  end

  test do
    assert_match "mtr-rs #{version}", shell_output("#{bin}/mtr-rs --version")
    assert_match "mtr-rs-packet", shell_output("#{bin}/mtr-rs --help")
  end
end
