# SPDX-License-Identifier: GPL-2.0-only
# Generated by scripts/homebrew-formula.sh in seitzbg/mtr-rs; edit there, not here.
class MtrRs < Formula
  desc "Rust port of mtr (My TraceRoute) with a terminal UI and classic reports"
  homepage "https://github.com/seitzbg/mtr-rs"
  version "0.4.1"
  license "GPL-2.0-only"

  on_macos do
    on_arm do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.4.1/mtr-rs-0.4.1-aarch64-macos.tar.gz"
      sha256 "ce9d45809ee67f767107d33ef7c657524e6ac6f44dce7675c4f5d3a36a68fe1b"
    end
    on_intel do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.4.1/mtr-rs-0.4.1-x86_64-macos.tar.gz"
      sha256 "487386b33962a24672bc3cd11150b965c25a2bd43410a2f4e2806e584b56e3fd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.4.1/mtr-rs-0.4.1-aarch64-linux.tar.gz"
      sha256 "3f3a7dd8b9321d2bff17e352021a705cec5fc6414105dbc075237a4f8b85627e"
    end
    on_intel do
      url "https://github.com/seitzbg/mtr-rs/releases/download/v0.4.1/mtr-rs-0.4.1-x86_64-linux.tar.gz"
      sha256 "636da18d6dffcad9116eaed47b8fa65de974c595de03e1e00151429021c34a35"
    end
  end

  def install
    bin.install "bin/mtr-rs", "bin/mtr-rs-packet"
    man8.install "man/mtr-rs.8", "man/mtr-rs-packet.8"
    bash_completion.install "completions/mtr-rs.bash" => "mtr-rs"
    zsh_completion.install "completions/_mtr-rs"
    fish_completion.install "completions/mtr-rs.fish"
  end

  def caveats
    # Accumulate rather than return from the last on_* block: on macOS that block is the
    # on_linux one, whose value is nil, and the caveat would silently vanish.
    text = +""
    on_macos do
      text << <<~EOS
        mtr-rs-packet opens raw sockets, which need root. Either run `sudo mtr-rs`, or let
        the helper start as root on its own (it drops back to you once its sockets are open);
        Homebrew cannot do that step, so repeat it after every install or upgrade:
          sudo chown root:wheel #{opt_bin}/mtr-rs-packet && sudo chmod u+s #{opt_bin}/mtr-rs-packet
      EOS
    end
    on_linux do
      text << <<~EOS
        mtr-rs-packet needs cap_net_raw for raw sockets; grant it once per install or upgrade:
          sudo setcap cap_net_raw+ep #{opt_bin}/mtr-rs-packet
        Without it the helper falls back to unprivileged ICMP sockets (see the README).
      EOS
    end
    text
  end

  test do
    assert_match "mtr-rs #{version}", shell_output("#{bin}/mtr-rs --version")
    assert_match "Usage: mtr-rs", shell_output("#{bin}/mtr-rs --help")
  end
end
